### ISSUE TITLE
Time error

### ISSUE THREAD

**Issue by pizza-777** [broxus/ever-wallet-browser-extension#3]
![Screenshot from 2023-04-23 00-08-56](https://user-images.githubusercontent.com/26024499/233807025-e981b2bc-9ab6-4a15-b4b8-ee301261854b.jpg)

Wrong transaction time

**Comment by Rexagon** [comment]
Wallet shows the correct time on this screenshot. You can find this transaction in the explorer.

If the screenshot was taken at the exact moment when the message was sent, you might have a wrong time on your machine. (extension uses jrpc/gql server time for replay protection so it works regardless of local clock).

**Comment by pizza-777** [comment]
> Wallet shows the correct time on this screenshot. You can find this transaction in the explorer.

This is the transaction in explorer https://everscan.io/transactions/9295fd532a4e8ed8e632f136b45f7c30ade7d061967b747aba2345ac77e89e6d 
![Screenshot from 2023-04-23 08-58-00](https://user-images.githubusercontent.com/26024499/233822483-640ba476-6a38-4118-9869-a7f3d973bdf1.png)

**Comment by Rexagon** [comment]
https://en.m.wikipedia.org/wiki/12-hour_clock 🙃

You can change the time display format in your system settings.

**Comment by pizza-777** [comment]
Got it. I didn't know before that 12:01 a.m. is equal to 00:01

Sorry for your time. The issue was dismissed.
